"""
This scripts extracts list of top 10 largest economies of the world
in descending order of their GDPs in Billion USD (to 2 d.p.), according to the IMF
"""

# Import necessary libraries
import numpy as np
import pandas as pd

# Supress warings generated by code
"""
def warn(*args, **kwargs):
    pass
import warnings
warnings.warn = warn
warnings.filterwarnings('ignore')
"""

# Extract required GDP data from 3rd table on URL using pandas
URL="https://web.archive.org/web/20230902185326/https://en.wikipedia.org/wiki/List_of_countries_by_GDP_%28nominal%29"
dfs_list = pd.read_html(URL)
gdp_df = dfs_list[3]

# Replace column headers with column numbers
gdp_df.columns = range(gdp_df.shape[1])

# Update gdp_df to only contain name of country and value of GDP
gdp_df = gdp_df[[0, 2]]

# Retain only rows 1 to 10 of gdp_df (row 0 is just total in the world)
gdp_df = gdp_df.iloc[1:11, :]

# Assign new collumn names as "Country" and "GDP (Million USD)"
gdp_df.columns = ["Country", "GDP (Million USD)"]

# Convert GDP values from million to billion USD
gdp_df[["GDP (Million USD)"]] = gdp_df[["GDP (Million USD)"]].astype(int)/1000

# Rename column header to "GDP (Billion USD)"
gdp_df = gdp_df.rename(columns = {"GDP (Million USD)": "GDP (Billion USD)"})

# Round values to 2 d.p.
gdp_df[["GDP (Billion USD)"]] = np.round(gdp_df[["GDP (Billion USD)"]], 2)

# Load dataframe into a csv file
gdp_df.to_csv("./Largest_economies.csv")